name: highdimensionalclustering
channels:
    - defaults
    - conda-forge
dependencies:
    - pip:
      - -e .
      - cdlib
      - gdown
      - igraph
      - leidenalg
      - nbdime
      - nbval
      - partition-igraph
      - pynndescent
      - python-dotenv>=0.5.1
    - bokeh
    - cairo
    - chardet
    - click
    - colorcet
    - conda-forge::hdbscan
    - conda-forge::rarfile
    - conda-forge::umap-learn
    - coverage
    - coveralls
    - datashader
    - fsspec
    - git>=2.5
    - holoviews
    - joblib
    - jupyter
    - jupyterlab
    - matplotlib
    - nb_conda_kernels
    - networkx
    - pandas
    - pathlib
    - pip
    - psutil
    - pycairo
    - python=3.9
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - setuptools
    - sphinx
    - wheel
